### ISSUE TITLE
libe57lib.a(E57FoundationImpl.cpp.o): undefined reference to symbol '_ZN11xercesc_3_26XMLUni20fgSAX2CoreNameSpacesE'？

### ISSUE THREAD

**Issue by frank0123** [madduci/PCD-E57#9] opened 2021-02-24 09:47 UTC
Hi, I'm trying to make this package **PCD-E57** to my project(also catkin). And it's compiled fine when catkin_make alone, however there's come the problem when apply it in another package, build error like this:

```
/usr/bin/ld: /home/xxx/xxx/install_isolated/lib/libe57lib.a(E57FoundationImpl.cpp.o): undefined reference to symbol '_ZN11xercesc_3_26XMLUni20fgSAX2CoreNameSpacesE'
/usr/lib/x86_64-linux-gnu/libxerces-c-3.2.so: Can't add symbol: DSO missing from command line
collect2: error: ld returned 1 exit status
```

It's seems the **xerces** problem, but I am confused that the package could compiled fine when alone, so the dependence of **xerces** is good. Why the error happens?

ENV: 

1.vtk6.3
2.libxerces-c-dev & libxerces-c3.2
3.ubuntu 18.04

**Comment by madduci** [comment] 2021-02-25 04:55
Hi @frank0123 

I believe you need to add Xerces explicitly to your target project (I'm assuming, you're using CMake too).

Something like:

```cmake
target_link_libraries(YOUR_TARGET libE57 xerces)
```

**Comment by frank0123** [comment] 2021-02-25 09:20
Yes. For me it's **xerces-c-3.2**.

**Comment by frank0123** [comment] 2021-03-01 02:26
Hi, @madduci 

I'm wonder it's possible to convert **ply** to **e57** by this library directly? Because I'm trying to do this indirectly, which means: at first convert the **ply** to **pcd**, and next convert **pcd** to **e57** with this library.

**Comment by madduci** [comment] 2021-03-02 15:32
Hi

sorry for the late reply, yes it is possible to convert to/from **PLY**, you have to change the Reader/Writer, selecting the PLY ones instead of the PCD ones.

**Comment by madduci** [comment] 2021-03-07 09:53
Closing as I can't reproduce the issue

**Closed as completed** 2021-03-07 09:52 UTC
